### ISSUE TITLE
Error: Unable to find item named 'SetPolarCoordinates' within ClassDef named 'wxPoint2DDouble'

### ISSUE THREAD

**Issue by programmingkidx** [pypy/wxpython-cffi#4]
When I was running this command "./build.py etg --generator=cffi --nodoc", it ended with this error:

Traceback (most recent call last):
  File "etg/geometry.py", line 130, in <module>
    run()
  File "etg/geometry.py", line 55, in run
    c.find('SetPolarCoordinates').ignore()
  File "/<PATH>/wxpython-cffi/etgtools/extractors.py", line 102, in find
    (head, self.__class__.__name__, self.name))
etgtools.extractors.ExtractorError: Unable to find item named 'SetPolarCoordinates' within ClassDef named 'wxPoint2DDouble'
Command '"/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python" etg/geometry.py --cffi --nodoc' failed with exit code 1.

**Comment by mattip** [comment]
Any ideas how to fix?
